USE Records;

DROP TABLE IF EXISTS Records;

CREATE TABLE Records (
    EntryID INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
    RecordDateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VideoPath VARCHAR(4096) DEFAULT NULL,
    PRIMARY KEY (EntryID)
)  CHARSET=UTF8;

